# Generated by Django 5.0.7 on 2024-07-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='image',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=8),
        ),
    ]
