version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: imgur_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: qwerty
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_NAME: imgur_db
      DATABASE_USER: mysql
      DATABASE_PASSWORD: qwerty
      DATABASE_HOST: db
      DATABASE_PORT: 3306

volumes:
  db_data: